wri/terramatch-microservices

- .github/workflows/pull-request.yml
- apps/research-service/src/site-polygons/dto/indicators.dto.ts
- apps/research-service/src/site-polygons/dto/site-polygon-update.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- apps/research-service/src/site-polygons/site-polygons.controller.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
- apps/research-service/src/site-polygons/site-polygons.service.spec.ts
- apps/research-service/src/site-polygons/site-polygons.service.ts
https://gfw.atlassian.net/browse/TM-1453
> [TM-1453] Bulk update indicators

- apps/job-service/src/jobs/dto/delayed-job.dto.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1536)
> [TM-1536] remove constructor

- apps/entity-service/src/trees/dto/establishment-trees.dto.ts
- apps/entity-service/src/trees/tree.service.spec.ts
- apps/entity-service/src/trees/tree.service.ts
- apps/entity-service/src/trees/trees.conroller.spec.ts
- apps/entity-service/src/trees/trees.controller.ts
- libs/database/src/lib/entities/tree-species.entity.ts
- libs/database/src/lib/factories/tree-species.factory.ts
A quick change to add the taxon id to the establishment tree data endpoint.
> [TM-1402] prepopulate tree rows

- README.md
- apps/entity-service/src/app.module.ts
- apps/entity-service/src/main.ts
- apps/job-service/src/app.module.ts
- apps/job-service/src/main.ts
- apps/research-service/src/app.module.ts
- apps/research-service/src/main.ts
- apps/unified-database-service/src/app.module.ts
- apps/unified-database-service/src/main.ts
- apps/user-service/src/app.module.ts
- apps/user-service/src/main.ts
- instrument-sentry.ts
- package-lock.json
- package.json
https://gfw.atlassian.net/browse/TM-1526
> [TM-1526] Integrate Sentry reporting.

- apps/unified-database-service/src/airtable/airtable.processor.spec.ts
- apps/unified-database-service/src/airtable/airtable.processor.ts
- apps/unified-database-service/src/airtable/airtable.service.spec.ts
- apps/unified-database-service/src/airtable/airtable.service.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.spec.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/tree-species.airtable-entity.ts
- apps/unified-database-service/src/webhook/dto/delete-records-query.dto.ts
- apps/unified-database-service/src/webhook/dto/update-records-query.dto.ts
- apps/unified-database-service/src/webhook/webhook.controller.spec.ts
- apps/unified-database-service/src/webhook/webhook.controller.ts
https://gfw.atlassian.net/browse/TM-1627
> [TM-1627] Deletion of records in Airtable that have been removed or hidden in the TM DB.

- apps/unified-database-service/src/airtable/airtable.processor.spec.ts
- apps/unified-database-service/src/airtable/airtable.processor.ts
- apps/unified-database-service/src/airtable/airtable.service.spec.ts
- apps/unified-database-service/src/airtable/airtable.service.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.spec.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/application.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/project.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/tree-species.airtable-entity.ts
- apps/unified-database-service/src/webhook/dto/update-records-query.dto.ts
- apps/unified-database-service/src/webhook/webhook.controller.spec.ts
- apps/unified-database-service/src/webhook/webhook.controller.ts
https://gfw.atlassian.net/browse/TM-1628
> [TM-1628] Support only sending records since a given updatedAt flag 

- .env.local.sample
- apps/unified-database-service/src/airtable/airtable.module.ts
- apps/unified-database-service/src/airtable/airtable.processor.spec.ts
- apps/unified-database-service/src/airtable/airtable.processor.ts
- apps/unified-database-service/src/airtable/airtable.service.spec.ts
- apps/unified-database-service/src/airtable/airtable.service.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.ts
- apps/unified-database-service/src/airtable/queue-health.service.ts
- apps/unified-database-service/src/app.module.ts
- apps/unified-database-service/src/health/health.controller.ts
- apps/unified-database-service/src/health/health.module.ts
- apps/unified-database-service/src/webhook/dto/update-all-query.dto.ts
- apps/unified-database-service/src/webhook/webhook.controller.spec.ts
- apps/unified-database-service/src/webhook/webhook.controller.ts
- package-lock.json
- package.json
https://gfw.atlassian.net/browse/TM-1522
Also included: 
* Slack update messages as processing takes place or errors out
* Health check on the redis connection
> [TM-1522] Daily syncs of the DB to Airtable.

- apps/unified-database-service/src/airtable/entities/airtable-entity.spec.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/project-report.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/project.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/restoration-partner.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/tree-species.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/workday.airtable-entity.ts
- libs/database/src/lib/constants/framework.ts
- libs/database/src/lib/entities/framework.entity.ts
- libs/database/src/lib/entities/project-report.entity.ts
- libs/database/src/lib/entities/project.entity.ts
https://gfw.atlassian.net/browse/TM-1675
> [TM-1675] Update some columns on project and project-report.

- apps/user-service/src/auth/auth.service.spec.ts
- apps/user-service/src/auth/auth.service.ts
- apps/user-service/src/auth/dto/login.dto.ts
- apps/user-service/src/auth/login.controller.spec.ts
- apps/user-service/src/auth/login.controller.ts
- apps/user-service/src/auth/reset-password.controller.spec.ts
- apps/user-service/src/users/users.controller.ts
https://gfw.atlassian.net/browse/TM-1713
> [TM-1713] Use UUID for logins / user find.

- apps/unified-database-service/src/airtable/entities/project.airtable-entity.ts
- libs/database/src/lib/entities/project.entity.ts
https://gfw.atlassian.net/browse/TM-1778
> [TM-1778] Send the project cohort to airtable.

- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
https://gfw.atlassian.net/browse/TM-1805
> [TM-1805] Only return active polygons.

- apps/research-service/src/main.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1759)
> [TM-1759] enable cors on research service

- .env.local.sample
- .github/workflows/deploy-service.yml
- libs/common/src/lib/email/email.service.spec.ts
- libs/common/src/lib/email/email.service.ts
https://gfw.atlassian.net/browse/TM-1814
> [TM-1814] Email Allowlist in lower envs

- apps/entity-service/src/main.ts
- apps/job-service/src/main.ts
- apps/research-service/src/main.ts
- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/dto/site-polygon.dto.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
- apps/unified-database-service/src/main.ts
- apps/user-service/src/main.ts
Return lightResource attribute for lightResource data
> [TM-1826] add light resource attrib

- apps/entity-service/src/entities/processors/nursery.processor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1767)
> [TM-1767] add missing fields to filter

- apps/entity-service/src/entities/processors/site.processor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1896)
> [TM-1896] add withAssociation on site search function

- .github/workflows/pull-request.yml
- apps/entity-service/src/entities/dto/entity-query.dto.ts
- apps/entity-service/src/entities/processors/project.processor.ts
- apps/entity-service/src/entities/processors/site.processor.spec.ts
- apps/entity-service/src/entities/processors/site.processor.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- libs/database/src/lib/util/paginated-query.builder.ts
https://gfw.atlassian.net/projects/TM/versions/10698/tab/release-report-all-issues
> [RELEASE] Agile Azurite Hotfix 2025 03 25

- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- apps/research-service/src/site-polygons/site-polygons.controller.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
- apps/research-service/src/site-polygons/site-polygons.service.spec.ts
- libs/database/src/lib/entities/index.ts
- libs/database/src/lib/entities/landscape-geometry.entity.ts
- libs/database/src/lib/entities/project.entity.ts
- libs/database/src/lib/factories/index.ts
- libs/database/src/lib/factories/landscape-geometry.factory.ts
- libs/database/src/lib/util/paginated-query.builder.ts
https://gfw.atlassian.net/browse/TM-1915
> [TM-1915] Site polygon filter updates for cohort / landscape boundary

- apps/entity-service/src/entities/processors/nursery-report.processor.spec.ts
- apps/entity-service/src/entities/processors/nursery-report.processor.ts
- apps/entity-service/src/entities/processors/project-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1941)
> [TM-1941] update entity reports procesors

- apps/entity-service/src/entities/processors/nursery-report.processor.spec.ts
- apps/entity-service/src/entities/processors/nursery-report.processor.ts
- apps/entity-service/src/entities/processors/project-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.ts
https://gfw.atlassian.net/projects/TM/versions/10797/tab/release-report-all-issues
> [RELEASE] Blazing Beryl Hotfix 2025 04 11

- .env.local.sample
- apps/entity-service/src/entities/entities.service.spec.ts
- apps/entity-service/src/entities/entities.service.ts
- apps/entity-service/src/entities/processors/association-processor.spec.ts
- apps/entity-service/src/entities/processors/entity.processor.spec.ts
- apps/entity-service/src/entities/processors/nursery-report.processor.spec.ts
- apps/entity-service/src/entities/processors/nursery-report.processor.ts
- apps/entity-service/src/entities/processors/nursery.processor.spec.ts
- apps/entity-service/src/entities/processors/project-report.processor.spec.ts
- apps/entity-service/src/entities/processors/project.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.ts
- apps/entity-service/src/entities/processors/site.processor.spec.ts
- jest.preset.js
- libs/common/src/lib/localization/localization.service.spec.ts
- libs/common/src/lib/localization/localization.service.ts
- libs/database/src/lib/factories/nursery-report.factory.ts
- libs/database/src/lib/factories/project-report.factory.ts
- libs/database/src/lib/factories/site-report.factory.ts
https://gfw.atlassian.net/browse/TM-1951
I also improved the report title generation code to correctly assemble and translate the title text.
> [TM-1951] Fix project report title in cases where a project report isn't found

- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- apps/research-service/src/site-polygons/site-polygons.controller.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
- apps/research-service/src/site-polygons/site-polygons.service.spec.ts
- libs/database/src/lib/entities/landscape-geometry.entity.ts
- libs/database/src/lib/entities/project.entity.ts
- libs/database/src/lib/factories/landscape-geometry.factory.ts
- libs/database/src/lib/types/landscapeGeometry.ts
https://gfw.atlassian.net/browse/TM-1915
> [TM-1915] Switch to using the project landscape string instead of the expensive geojson intersect query.

- apps/unified-database-service/src/airtable/entities/funding-programme.airtable-entity.ts
https://gfw.atlassian.net/browse/TM-1882
> [TM-1882] Send the raw framework key for funding programmes

- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/dto/site-polygon.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
https://gfw.atlassian.net/browse/TM-1915
> [TM-1915] Include projectId in site polygons response

- apps/entity-service/src/entities/dto/nursery-report.dto.ts
- apps/entity-service/src/entities/dto/nursery.dto.ts
- apps/entity-service/src/entities/dto/project-report.dto.ts
- apps/entity-service/src/entities/dto/site-report.dto.ts
- apps/entity-service/src/entities/processors/nursery-report.processor.ts
- apps/entity-service/src/entities/processors/project-report.processor.ts
- apps/entity-service/src/entities/processors/site-report.processor.ts
- libs/database/src/lib/entities/nursery.entity.ts
https://gfw.atlassian.net/browse/TM-1774
> [TM-1774] Remove use of migrated flag in be ms

- libs/database/src/lib/util/paginated-query.builder.ts
https://gfw.atlassian.net/browse/TM-1960
> [TM-1960] To get a true count, we need to query with distinct.

- apps/entity-service/src/entities/dto/project-report.dto.ts
- apps/entity-service/src/entities/dto/site-report.dto.ts
- libs/database/src/lib/entities/project-report.entity.ts
- libs/database/src/lib/entities/site-report.entity.ts
[Task Link](https://gfw.atlassian.net/browse/TM-1942)
> [TM-1942] add new fields to fields in projects and site reports

- libs/common/src/lib/email/email.service.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2010)
> [TM-2010] Unable to sign up as a new user

- cdk/service-stack/lib/service-stack.ts
- cdk/service-stack/package-lock.json
https://gfw.atlassian.net/browse/TM-1931
> [TM-1931] Modify configurations for cpu / memory based on AWS recommendations

- .github/workflows/deploy-api-gateway.yml
- .github/workflows/deploy-services.yml
- .github/workflows/start-env.yml
- .github/workflows/stop-env.yml
- README.md
- cdk/service-stack/package-lock.json
https://gfw.atlassian.net/browse/TM-1931
> [TM-1931] Github Actions for starting / stopping an entire env.

- apps/entity-service/src/entities/dto/project-report.dto.ts
- apps/entity-service/src/entities/processors/project-report.processor.ts
- libs/database/src/lib/entities/demographic.entity.ts
- libs/database/src/lib/entities/project-report.entity.ts
https://gfw.atlassian.net/browse/TM-1969
The ticket mentions planting data, but it also has an incorrect site report export linked, so I'm waiting to hear back from Claire on whether the tree data is correct or not. From the code, I think it should be so I'm opening the PR, but there might be more changes coming based on feedback from Claire.
> [TM-1969] Aggregate workday total from all reports in the task

- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- libs/database/src/lib/entities/site-polygon.entity.ts
https://gfw.atlassian.net/projects/TM/versions/10995/tab/release-report-all-issues
> [RELEASE] Dazzling Diamond Hotfix 2025 05 07

- apps/unified-database-service/src/airtable/entities/project-pitch.airtable-entity.ts
- libs/database/src/lib/entities/project-pitch.entity.ts
https://gfw.atlassian.net/browse/TM-2063
> [TM-2063] Add org UUID to the pitches table in Airtable.

- apps/entity-service/src/entities/dto/project-pitch.dto.ts
- libs/database/src/lib/entities/project-pitch.entity.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2038)
> [TM-2038] add new fields to project pitches

- .github/workflows/deploy-service.yml
- .github/workflows/deploy-services.yml
[Task Link](https://gfw.atlassian.net/browse/TM-2008)
> [TM-2008] update deploy services

- apps/entity-service/src/entities/dto/entity-query.dto.ts
- apps/entity-service/src/entities/dto/project.dto.ts
- apps/entity-service/src/entities/processors/project.processor.ts
- libs/database/src/lib/entities/project.entity.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2049)
> [TM-2049] add project short name column filter

- libs/database/src/lib/constants/demographic-collections.ts
- libs/database/src/lib/entities/demographic.entity.ts
https://gfw.atlassian.net/browse/TM-2054
> [TM-2054] Add new demographics types / collections

- apps/unified-database-service/src/airtable/airtable.processor.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.spec.ts
- apps/unified-database-service/src/airtable/entities/financial-indicator.airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/index.ts
- libs/database/src/lib/entities/financial-indicator.entity.ts
- libs/database/src/lib/entities/index.ts
- libs/database/src/lib/factories/financial-indicator.factory.ts
- libs/database/src/lib/factories/index.ts
https://gfw.atlassian.net/browse/TM-2068
> [TM-2068] Add financial indicators to airtable.

- apps/unified-database-service/src/airtable/entities/financial-indicator.airtable-entity.ts
- libs/database/src/lib/entities/financial-indicator.entity.ts
https://gfw.atlassian.net/browse/TM-2068
> [TM-2068] Add the missing "year" field.

- apps/unified-database-service/src/airtable/entities/project-pitch.airtable-entity.ts
- libs/database/src/lib/entities/project-pitch.entity.ts
https://gfw.atlassian.net/browse/TM-2209
> [TM-2209] Fix the association from project pitch to org in AT

- apps/entity-service/src/entities/dto/project-report.dto.ts
- libs/database/src/lib/entities/project-report.entity.ts
https://gfw.atlassian.net/browse/TM-2115
> [TM-2115] add new collection names for media options

- apps/entity-service/src/entities/dto/disturbance.dto.ts
- libs/database/src/lib/entities/disturbance.entity.ts
[Task link ](https://gfw.atlassian.net/browse/TM-2221)
> [TM-2221] feat(TM-2221): update disturbance dto and entity

- apps/dashboard-service/src/app.module.ts
- apps/dashboard-service/src/dashboard/dto/cache.service.spec.ts
- apps/dashboard-service/src/dashboard/dto/cache.service.ts
- apps/dashboard-service/src/dashboard/warmup/dashboard-cache-warmup.service.ts
https://gfw.atlassian.net/browse/TM-2225
> [TM-2225] Implement automatic cache update for dashboard

- apps/entity-service/src/entities/dto/nursery.dto.ts
- apps/entity-service/src/entities/dto/project.dto.ts
- apps/entity-service/src/entities/dto/site.dto.ts
- apps/research-service/src/site-polygons/dto/site-polygon.dto.ts
- libs/database/src/lib/constants/index.ts
- libs/database/src/lib/constants/planting-status.ts
- libs/database/src/lib/entities/nursery.entity.ts
- libs/database/src/lib/entities/project.entity.ts
- libs/database/src/lib/entities/site-polygon.entity.ts
- libs/database/src/lib/entities/site.entity.ts
[task link](https://gfw.atlassian.net/browse/TM-2235)
> [TM-2235] Create planting_status field

- apps/entity-service/src/entities/processors/site-report.processor.spec.ts
- apps/entity-service/src/entities/processors/site-report.processor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2236)
> [TM-2236] add logic to ppc site report title

- apps/dashboard-service/src/dashboard/constants/dashboard-entities.constants.ts
- apps/dashboard-service/src/dashboard/dashboard-entities.controller.spec.ts
https://gfw.atlassian.net/browse/TM-2295
> [TM-2295] rename dashboardSitePolygons to dashboardSitepolygons

- apps/dashboard-service/src/dashboard/dashboard-entities.controller.spec.ts
- apps/dashboard-service/src/dashboard/dashboard-entities.controller.ts
https://gfw.atlassian.net/browse/TM-2295
> [TM-2295] send always full dto for single project in dashboard

- apps/dashboard-service/src/dashboard/dashboard-entities.controller.ts
https://gfw.atlassian.net/browse/TM-2341
> [TM-2341] fix stored cache for sitepolygons

- libs/common/src/lib/media/media.service.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2292)
> [TM-2292] Fix Thumbnail jpeg

- apps/research-service/src/bounding-boxes/bounding-box.controller.spec.ts
- apps/research-service/src/bounding-boxes/bounding-box.controller.ts
https://gfw.atlassian.net/browse/TM-2358
> [TM-2358] remove policies from no bearer

- apps/research-service-e2e/src/research-service/research-service.spec.ts
- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/dto/site-polygon.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.spec.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.ts
- apps/research-service/src/site-polygons/site-polygons.controller.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
- apps/research-service/src/site-polygons/site-polygons.service.spec.ts
- apps/research-service/src/site-polygons/site-polygons.service.ts
- libs/common/src/lib/policies/site-polygon.policy.ts
- libs/database/src/lib/entities/site-polygon.entity.ts
https://gfw.atlassian.net/browse/TM-2334
> [TM-2334] update policy for sitePolygons

- .env.local.sample
- .github/workflows/deploy-service.yml
- libs/common/src/lib/analytics/analytics-events.service.ts
- libs/common/src/lib/analytics/analytics.processor.ts
- libs/common/src/lib/common.module.ts
- libs/common/src/lib/events/entity-status-update.event-processor.ts
- libs/common/src/lib/events/event.processor.ts
- libs/common/src/lib/events/event.service.ts
- libs/common/src/lib/util/bootstrap-repl.ts
- libs/database/src/lib/constants/status.ts
- libs/database/src/lib/entities/audit-status.entity.ts
- libs/database/src/lib/entities/nursery-report.entity.ts
- libs/database/src/lib/entities/nursery.entity.ts
- libs/database/src/lib/entities/project-report.entity.ts
- libs/database/src/lib/entities/project.entity.ts
- libs/database/src/lib/entities/site-polygon.entity.ts
- libs/database/src/lib/entities/site-report.entity.ts
- libs/database/src/lib/entities/site.entity.ts
- libs/database/src/lib/types/util.ts
https://gfw.atlassian.net/browse/TM-2031
> [TM-2031] Send a google analytics event when an entity or site polygon status changes

- apps/unified-database-service/src/airtable/entities/airtable-entity.spec.ts
- apps/unified-database-service/src/airtable/entities/project.airtable-entity.ts
https://gfw.atlassian.net/browse/TM-2377
> [TM-2377] Only consider approved polygons for calculated hectares restored to date.

- apps/unified-database-service/src/airtable/entities/project-report.airtable-entity.ts
[task link](https://gfw.atlassian.net/browse/TM-2346)
> [TM-2346] Add the v2_project_reports.convergence_amount field to the Airtable API

- .github/workflows/stop-env.yml
> Include the dashboard service the stop env action.

- apps/research-service/src/site-polygons/dto/site-polygon-query.dto.ts
- apps/research-service/src/site-polygons/site-polygon-query.builder.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.spec.ts
- apps/research-service/src/site-polygons/site-polygons.controller.ts
https://gfw.atlassian.net/browse/TM-2387
> [TM-2387] add sorting for sitepolygons

- apps/entity-service/src/app.module.ts
- apps/entity-service/src/forms/dto/option-label.dto.ts
- apps/entity-service/src/forms/option-labels.controller.spec.ts
- apps/entity-service/src/forms/option-labels.controller.ts
- cdk/api-gateway/lib/api-gateway-stack.ts
- libs/database/src/lib/entities/form-option-list-option.entity.ts
- libs/database/src/lib/entities/form-option-list.entity.ts
- libs/database/src/lib/entities/i18n-item.entity.ts
- libs/database/src/lib/entities/index.ts
- libs/database/src/lib/entities/user.entity.ts
- libs/database/src/lib/factories/form-option-list-option.factory.ts
- libs/database/src/lib/factories/form-question-option.factory.ts
- libs/database/src/lib/factories/index.ts
https://gfw.atlassian.net/browse/TM-2413
> [TM-2413] Initial option labels v3 endpoint

- apps/unified-database-service/src/airtable/airtable.processor.ts
- apps/unified-database-service/src/airtable/entities/airtable-entity.ts
- apps/unified-database-service/src/airtable/entities/users.airtable-entity.ts
https://gfw.atlassian.net/browse/TM-2426
> [TM-2426] Implement the Users table in airtable.

- apps/entity-service/src/entities/dto/financial-report.dto.ts
- apps/entity-service/src/entities/processors/financial-report.processor.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2301)
> [TM-2301] add update request field

- apps/dashboard-service/src/dashboard/dashboard-entities.controller.spec.ts
- apps/dashboard-service/src/dashboard/dashboard-entities.controller.ts
https://gfw.atlassian.net/browse/TM-2380
> [TM-2380] avoid caching impact story list for dashboard

- libs/common/src/lib/email/entity-status-update.email.ts
- libs/common/src/lib/events/entity-status-update.event-processor.spec.ts
- libs/database/src/lib/constants/entities.ts
[Task Link](https://gfw.atlassian.net/browse/TM-2442)
> [TM-2442] Enable mails for financial reports

- apps/dashboard-service/src/dashboard/hectares-restoration.service.ts
https://gfw.atlassian.net/browse/TM-2476
> [TM-2476] validate numbers in hectares under restoration for dashbaord

- apps/entity-service/src/trees/dto/establishment-trees.dto.ts
- apps/entity-service/src/trees/dto/species.dto.ts
- apps/entity-service/src/trees/dto/tree-report-counts.dto.ts
- apps/entity-service/src/trees/tree.service.spec.ts
- apps/entity-service/src/trees/tree.service.ts
- apps/entity-service/src/trees/trees.controller.spec.ts
- apps/entity-service/src/trees/trees.controller.ts
- libs/database/src/lib/factories/seeding.factory.ts
https://gfw.atlassian.net/browse/TM-2449
> [TM-2449] Return taxon id with establishment species.

- apps/entity-service/src/forms/linked-fields.controller.ts
https://gfw.atlassian.net/browse/TM-2412
> [TM-2412] Fix the index meta for requests with no form types specified.

- libs/common/src/lib/linkedFields/configuration/project-pitch.configuration.ts
- libs/database/src/lib/entities/project-pitch.entity.ts
https://gfw.atlassian.net/browse/TM-2485
> [TM-2485] Add two new project pitch fields for Fundo Flora

- apps/entity-service/src/entities/dto/project-report.dto.ts
- apps/entity-service/src/entities/dto/site-report.dto.ts
- libs/common/src/lib/linkedFields/configuration/project-report.configuration.ts
- libs/common/src/lib/linkedFields/configuration/site-report.configuration.ts
- libs/database/src/lib/entities/project-report.entity.ts
- libs/database/src/lib/entities/site-report.entity.ts
[task link](https://gfw.atlassian.net/browse/TM-2488)
> [TM-2488] Add planting status dropdown to site/project report forms
